### ISSUE TITLE
How to handle global navigator reference on the server side

### ISSUE THREAD

**Issue by jwixel** [sveltejs/sapper#1027]
I'm trying to use https://github.com/visjs/vis-timeline in a sapper project.  `vis-timeline` assumes it's being loaded in a browser and uses that assumption to try to derive locale (https://github.com/visjs/vis-timeline/blob/master/lib/DOMutil.js#L226-L232).  The sapper server crashes because of the undefined reference:

```
ReferenceError: navigator is not defined
    at pl (/home/billywill/Projects/myproject/node_modules/vis-timeline/dist/vis-timeline-graph2d.min.js:26:124620)
    at /home/billywill/Projects/myproject/node_modules/vis-timeline/dist/vis-timeline-graph2d.min.js:52:434744
    at /home/billywill/Projects/myproject/node_modules/vis-timeline/dist/vis-timeline-graph2d.min.js:26:69
    at Object.<anonymous> (/home/billywill/Projects/myproject/node_modules/vis-timeline/dist/vis-timeline-graph2d.min.js:26:169)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
> Server crashed
```

Is there a recommended way to handle defining `navigator` for the server?

**Comment by antony** [comment]
This is covered in the documentation https://sapper.svelte.dev/docs#Server-side_rendering

**Comment by jwixel** [comment]
thanks!
