### ISSUE TITLE
Compile a Sapper app using the Sapper module

### ISSUE THREAD

**Issue by jensb1** [sveltejs/sapper#1029]
I playing around with Sapper and is experimenting with compiling the code outside the Sapper module. I need this for for an app-builder I am thinking about building. My project structure is quite simple:

**Would really appreciate some tips on how I can proceed, thanks!**

```
dist
node_modules
package.json
rollup.config.js
runtime
	app.mjs (copied from Sapper)
	shared.mjs (copied from Sapper)
	internal/
		error.svelte
		layout.svelte
		shared.mjs
src
	index.js
yarn-error.log
yarn.lock
```

I'm stuck pretty early, probably because Im not very experienced with latest nodejs development (coming from ruby etc). The rollup build complain on: 

```
../node_modules/sapper/dist/index.js: (89:9)
[!] Error: Duplicate export '__moduleExports'
```

If I make a infile patch of the compiled sapper/dist/index.js file and remove the __moduleExports line it compiles ok. If I then try to run the compiled index.js:

```
➜  git:(master)> node dist/index.js
TypeError: commonjsRequire.resolve is not a function
    at Object.copy_shimport (INSERTPATH/dist/index.js:2087:35)
    at build (INSERTPATH/dist/index.js:2215:9)
    at INSERTPATH/dist/index.js:2320:10
    at Object.<anonymous> (INSERTPATH/dist/index.js:2325:3)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

```

The experiment i am doing is quite simple, I am trying to import the compiled files from the module (sapper/dist/*), for example:
```
import {build} from 'sapper/dist/build.js';

(async () => {

		// This works if I include sapper/dist/core.js
		// let manifest_data = core.create_manifest_data("[YOURPATH]/src/routes", ".svelte .html");

		let bundler = "rollup";
		let cwd =  "INSERTTARGETAPPPATH";
		let src = "INSERTTARGETAPPPATH/src";
		let dest = "INSERTTARGETAPPPATH/__sapper__/dev"
		let routes ="INSERTTARGETAPPPATH/src/routes"
		let output = "INSERTTARGETAPPPATH/src/node_modules/@sapper"

		try {
			await build({cwd: cwd, src: src, routes: routes, output: output, dest: dest, bundler: bundler, ext: ".svelte .html"});
		} catch(err) {
			console.log(err);
		}

})();
```

with rollup.config.js:
```
import { string } from 'rollup-plugin-string';
import json from 'rollup-plugin-json';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import pkg from './package.json';
import { builtinModules } from 'module';

const external = [].concat(
	Object.keys(pkg.dependencies),
	Object.keys(process.binding('natives')),
	'svelte/compiler'
);
console.log(external);

export default [
	{
		input: [
			`src/index.js`,
		],
		output: {
			dir: 'dist',
			format: 'cjs',
			sourcemap: true
		},
		external,
		plugins: [
			json(),
			resolve(),
			commonjs(),

		]
	}
];
```

**Comment by antony** [comment]
Hi @jensb1 - pleased that you're considering using Sapper as part of an app builder. I think it's a good choice.

Github issues is really not the right place to help you with this though. Please close this issue and come and have a chat to us in the [Svelte Discord](https://svelte.dev/chat). We're friendly I promise!

**Comment by jensb1** [comment]
Cool, will repost there. Thanks
