### ISSUE TITLE
`sapper build` breaks when passing --cwd and [dest]

### ISSUE THREAD

**Issue by mikeparisstuff** [sveltejs/sapper#1074]
**Describe the bug**
I believe I have found a small bug in how paths are resolved when using both `--cwd` and a `[dest]` in `sapper build`. I have been trying to move a sapper project to build within bazel which led me to discover this.

I am trying to run this sapper command:

```
sapper build relative/path/to/output/dir --legacy --cwd ./relative/path/to/sapper-app --bundler rollup
```

My `rollup.config.js` is at path `./relative/path/to/sapper-app/rollup.config.js` and if I don't provide a `cwd` then sapper is unable to find it. 

The problem is that if you run this, then you will see an `index.js` at `relative/path/to/output/dir/index.js` but the rest of the sapper project build is saved to `./relative/path/to/sapper-app/relative/path/to/output/dir`. It looks like the [path resolved here](https://github.com/sveltejs/sapper/blob/d99d67bbb1ca0bc1cbb923392c6f5530518763ff/src/cli.ts#L174) is going to end up being different than the [path resolved here](https://github.com/sveltejs/sapper/blob/d99d67bbb1ca0bc1cbb923392c6f5530518763ff/src/api/build.ts#L43) which results in the problem that I am seeing.

Without thinking too hard, I think there may be a few fixes.

1. Update the [the first path](https://github.com/sveltejs/sapper/blob/d99d67bbb1ca0bc1cbb923392c6f5530518763ff/src/cli.ts#L174) to take into account the `--cwd`.
2. Add more options to `build`. E.G. if I could set a `--config` path and a `--src` path then I wouldn't need to change the `--cwd` and all relative paths would work again.
3. Force `[dest]` into an absolute path in the `cli` [perhaps here?](https://github.com/sveltejs/sapper/blob/d99d67bbb1ca0bc1cbb923392c6f5530518763ff/src/cli.ts#L172) using `path.resolve`. I think this would require changing how `--cwd` works tho so option (1) is probably better.

I have looked into alternatives to try to force absolute paths in bazel but this is not only much harder as you need to slightly tweak a lot of default build rules and seems to be a bad practice.

**To Reproduce**
To reproduce, run sapper build with both a `[dest]` and a `--cwd` from a parent directory. E.G. if you have a project at `/Users/me/projects/sapper-app` run the following from the path `/Users/me/projects`.

```
sapper build ./sapper_out --legacy --cwd "./sapper-app" --bundler rollup
```

You will see the following:

```
/Users/me/projects/sapper_out
    /index.js
/Users/me/projects/sapper-app/sapper_out
   /build.json
   /template.html
   /service-worker.js
   /client/
   /server/
```

As you can see the directory appears to be split into two locations.

**Comment by mikeparisstuff** [comment]
I've been working on fixing this in the PR linked above but am running into a few complications. The `--cwd` argument seems to be only partially supported as some places use it and others don't. I'm also running into an issue where the `--cwd` passed at  build time impacts the result at runtime as some of the same paths are referenced in the server_manifest and other places. I'm going to keep digging through this.

**Comment by mikeparisstuff** [comment]
The newest problem is this set of lines:
- https://github.com/sveltejs/sapper/blob/22389eab992355b948ca6ce5a28e39ab1947ccac/src/core/create_app.ts#L182 
- https://github.com/sveltejs/sapper/blob/22389eab992355b948ca6ce5a28e39ab1947ccac/src/core/create_app.ts#L234

The PR linked above fixes the build time issues and allows you to run:

```
sapper build ../../sap --cwd ./client/svelte-sapper --bundler rollup
```

I have a requirement to save the build to a directory outside of the source directory as specified by `--cwd` so I need the `..` with the current fix. The above command executes successfully and leaves a seemingly good looking build at `./sap` relative to where I ran the command above. The problem is that that the generated `server/server.js` has a hard coded pointer to `../../sap` so when I try to run `node ./sap` from the same directory, I get this error:

```bash
Starting server on port 3000
fs.js:126
    throw err;
    ^

Error: ENOENT: no such file or directory, open '../../sap/build.json'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at get_page_handler (/Users/michaelparis/Projects/motley/sap/server/server.js:2687:65)
    at middleware (/Users/michaelparis/Projects/motley/sap/server/server.js:3115:3)
    at Object.<anonymous> (/Users/michaelparis/Projects/motley/sap/server/server.js:3191:3)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '../../sap/build.json'
}
```

See https://github.com/sveltejs/sapper/blob/22389eab992355b948ca6ce5a28e39ab1947ccac/src/core/create_app.ts#L234. I'm now wondering why we need this hard coded path. The `server/server.js` file is already in the build so perhaps we can load files relative to it?

More generally, I wonder if it would be reasonable to add a `--src_dir` (or `--project_dir` to avoid confusion with `--src`) option to build that does not make any assumptions about changing the `--cwd`. This would allow someone to write:

```
sapper build ./sap --src_dir ./client/svelte-sapper --bundler rollup
```

The semantics are similar and you would be able to start a build from anywhere on the machine and output it to any other point on the machine keeping things relative to where you are running the command from instead of relative to where the source directory lies. This would fix the runtime error I am getting above because the `build_dir` would be `./sap` again which allows me to run the build from the same location that started the build (which works for my use case). I still think it would be worth looking into if its easily possible to make everything in the build directory relative to the root of the build directory. The main goal would be that you would be able to start a build from anywhere `sapper build builds/output/project --src_dir somewhere/else/project` as well as start the server from anywhere e.g. `node ../../builds/output/project`. Currently it seems like the build and server start commands need to be run from the same relative cwd to the `[dest]`.

**Comment by ajbouh** [comment]
Hi @mikeparisstuff, how far did you get in terms of bazel support?
