### ISSUE TITLE
Using svelte/register: require.extensions is not supported by webpack.

### ISSUE THREAD

**Issue by soullivaneuh** [sveltejs/sapper#1080]
**Describe the bug**

The server crash when I add `require('svelte/register');` on a sapper route.

**Logs**

```
src/routes/rides/[id].pdf.js changed. rebuilding...
• server
node_modules/svelte/register.js 23:8-26
require.extensions is not supported by webpack. Use a loader instead.
node_modules/svelte/register.js 27:1-19
require.extensions is not supported by webpack. Use a loader instead.
webpack:///./node_modules/svelte/register.js?:27
        (void 0)[extension] = function(module, filename) {
                            ^

TypeError: Cannot set property '.svelte' of undefined
    at registerExtension (webpack:///./node_modules/svelte/register.js?:27:22)
    at eval (webpack:///./node_modules/svelte/register.js?:45:1)
    at Object../node_modules/svelte/register.js (/home/sullivan/p/gitlab.com/kidways/admin/__sapper__/dev/server/server.js:2461:1)
    at __webpack_require__ (/home/sullivan/p/gitlab.com/kidways/admin/__sapper__/dev/server/server.js:27:30)
    at eval (webpack:///./src/routes/rides/./src/routes/rides/%5Bid%5D.pdf.js.pdf.js?:6:1)
    at Module../src/routes/rides/[id].pdf.js (/home/sullivan/p/gitlab.com/kidways/admin/__sapper__/dev/server/server.js:2686:1)
    at __webpack_require__ (/home/sullivan/p/gitlab.com/kidways/admin/__sapper__/dev/server/server.js:27:30)
    at eval (webpack:///./src/node_modules/@sapper/internal/manifest-server.mjs?:6:81)
    at Module../src/node_modules/@sapper/internal/manifest-server.mjs (/home/sullivan/p/gitlab.com/kidways/admin/__sapper__/dev/server/server.js:2614:1)
    at __webpack_require__ (/home/sullivan/p/gitlab.com/kidways/admin/__sapper__/dev/server/server.js:27:30)
> Server crashed
```

**To Reproduce**

The goal is to load a Svelte component and render the html to a pdf:

```javascript
require('svelte/register');
import { RideInfo } from './RideInfo.svelte';
import { pipe, gotenberg, convert, html, please } from 'gotenberg-js-client'

const toPDF = pipe(
  gotenberg('https://pdf.service'),
  convert,
  html,
  please
)

export async function get(req, res, next) {
  const pdf = await toPDF(RideInfo.render(data));

  pdf.pipe(res);
}
```

It crashes directly on `require('svelte/register');`.

**Expected behavior**

Having the server working as expected.

Maybe I'm mistaking how to implement pdf conversion of a specific svelte component, I'm hearing suggestions.

Note: In that concrete case, I don't want to render a full sapper ssr page on a pdf, just an internal svelte component. The goal is to avoid useless things like the navbar.

**Information about your Sapper Installation:**
- Your browser and the version: Not relevant
- Your operating system: Linux sweethome 4.19.79-1-MANJARO #1 SMP PREEMPT Fri Oct 11 19:57:09 UTC 2019 x86_64 GNU/Linux
- Your hosting environment: Local
- Sapper version: 0.27.9
- Svelte version: 3.17.3 (also tested 3.18.1 without any luck)
- It's a dynamic application.
- I use Webpack

**Severity**

This is blocking my sapper usage completely for this feature. I didn't find any solution/workaround so far.

**Additional context**

Here is the Webpack configuration:

```javascript
const webpack = require('webpack');
const path = require('path');
const config = require('sapper/config/webpack.js');
const dotenv = require('dotenv');

const pkg = require('./package.json');

const mode = process.env.NODE_ENV;
const dev = mode === 'development';

const alias = { svelte: path.resolve('node_modules', 'svelte') };
const extensions = ['.mjs', '.js', '.json', '.svelte', '.html'];
const mainFields = ['svelte', 'module', 'browser', 'main'];

dotenv.config();

module.exports = {
  client: {
    entry: config.client.entry(),
    output: config.client.output(),
    resolve: {
      alias,
      extensions,
      mainFields,
    },
    module: {
      rules: [
        {
          test: /\.(svelte|html)$/,
          use: {
            loader: 'svelte-loader',
            options: {
              dev,
              hydratable: true,
              hotReload: true,
            },
          },
        },
      ],
    },
    mode,
    plugins: [
      // pending https://github.com/sveltejs/svelte/issues/2377
      // dev && new webpack.HotModuleReplacementPlugin(),
      new webpack.DefinePlugin({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode),
        'process.env.API_ENDPOINT': JSON.stringify(
          process.env.API_ENDPOINT || 'undefined',
        ),
      }),
    ].filter(Boolean),
    devtool: dev && 'inline-source-map',
  },

  server: {
    entry: config.server.entry(),
    output: config.server.output(),
    target: 'node',
    resolve: {
      alias,
      extensions,
      mainFields,
    },
    externals: Object.keys(pkg.dependencies).concat('encoding'),
    module: {
      rules: [
        {
          test: /\.(svelte|html)$/,
          use: {
            loader: 'svelte-loader',
            options: {
              css: false,
              generate: 'ssr',
              dev,
            },
          },
        },
      ],
    },
    mode: process.env.NODE_ENV,
    performance: {
      hints: false, // it doesn't matter if server.js is large
    },
  },

  serviceworker: {
    entry: config.serviceworker.entry(),
    output: config.serviceworker.output(),
    mode: process.env.NODE_ENV,
  },
};
```

I'm not especially attached to Webpack. If it's a limitation of the tool, I'm ok to switch to rollup.

**Comment by sw-yx** [comment]
i dont think svelte/register is designed for this. why must you use webpack at all? svelte/register is meant for Node usage without bundler, as per the docs

**Comment by pngwn** [comment]
As @sw-yx said, this isn’t the intended usage for `svelte/register`. If you ask via one of the support channels we can try to solve your issue some other way.
