### ISSUE TITLE
Babel does not seem to work with modern ES syntax

### ISSUE THREAD

**Issue by iOiurson** [sveltejs/sapper#1128]
In `.js` files, recent ES syntax like optional chaining are not supported.

The following snippet is imported in `index.svelte`.
```js
// in test.js
let a;
console.log('test', a?.b);
console.log('test', a ?? 'hey');
```

**Logs**
```
✗ server
Unexpected token (2:22) in /Users/Romain/Code/perso/open-books/src/test.js
1: let a;
2: console.log('test', a?.b);
                         ^
✗ client
Unexpected token (2:22) in /Users/Romain/Code/perso/open-books/src/test.js
1: let a;
2: console.log('test', a?.b);
                         ^
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/Users/Romain/Code/perso/open-books/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Server crashed
✔ service worker (126ms)
```

I'm using Rollup with the following config:

**`package.json` dev dependencies**
```json
...
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.9.0",
    "@babel/runtime": "^7.9.0",
    "@rollup/plugin-commonjs": "^11.0.0",
    "@rollup/plugin-node-resolve": "^7.0.0",
    "@rollup/plugin-replace": "^2.2.0",
    "node-sass": "^4.13.1",
    "npm-run-all": "^4.1.5",
    "rollup": "^1.20.0",
    "rollup-plugin-babel": "^4.0.2",
    "rollup-plugin-svelte": "^5.0.1",
    "rollup-plugin-terser": "^5.2.0",
    "sapper": "^0.27.11",
    "svelte": "^3.20.1",
    "svelte-preprocess": "^3.5.0"
  }
```

**`rollup.config.js`**
```js
import resolve from '@rollup/plugin-node-resolve';
import replace from '@rollup/plugin-replace';
import commonjs from '@rollup/plugin-commonjs';
import svelte from 'rollup-plugin-svelte';
import babel from 'rollup-plugin-babel';
import { terser } from 'rollup-plugin-terser';
import sveltePreprocess from 'svelte-preprocess';
import config from 'sapper/config/rollup.js';
import pkg from './package.json';

const mode = process.env.NODE_ENV;
const dev = mode === 'development';
const legacy = !!process.env.SAPPER_LEGACY_BUILD;

const onwarn = (warning, onwarn) =>
  (warning.code === 'CIRCULAR_DEPENDENCY' &&
    /[/\\]@sapper[/\\]/.test(warning.message)) ||
  onwarn(warning);

const preprocess = sveltePreprocess({
  babel: {
    presets: [
      [
        '@babel/preset-env',
        {
          loose: true,
          // No need for babel to resolve modules
          modules: false,
          targets: {
            // ! Very important. Target es6+
            esmodules: true,
          },
        },
      ],
    ],
  },
});

export default {
  client: {
    input: config.client.input(),
    output: config.client.output(),
    plugins: [
      replace({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),
      svelte({
        preprocess,
        dev,
        hydratable: true,
        emitCss: true,
      }),
      resolve({
        browser: true,
        dedupe: ['svelte'],
      }),
      commonjs(),

      legacy &&
        babel({
          extensions: ['.js', '.mjs', '.html', '.svelte'],
          runtimeHelpers: true,
          exclude: ['node_modules/@babel/**'],
          presets: [
            [
              '@babel/preset-env',
              {
                targets: '> 0.25%, not dead',
              },
            ],
          ],
          plugins: [
            '@babel/plugin-syntax-dynamic-import',
            [
              '@babel/plugin-transform-runtime',
              {
                useESModules: true,
              },
            ],
          ],
        }),

      !dev &&
        terser({
          module: true,
        }),
    ],

    onwarn,
  },

  server: {
    input: config.server.input(),
    output: config.server.output(),
    plugins: [
      replace({
        'process.browser': false,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),
      svelte({
        preprocess,
        generate: 'ssr',
        dev,
      }),
      resolve({
        dedupe: ['svelte'],
      }),
      commonjs(),
    ],
    external: Object.keys(pkg.dependencies).concat(
      require('module').builtinModules ||
        Object.keys(process.binding('natives')),
    ),

    onwarn,
  },

  serviceworker: {
    input: config.serviceworker.input(),
    output: config.serviceworker.output(),
    plugins: [
      resolve(),
      replace({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),
      commonjs(),
      !dev && terser(),
    ],

    onwarn,
  },
};

```

**Comment by Conduitry** [comment]
Svelte itself does not yet support parsing or handling this syntax (blocked by the parser we're using not supporting them, which itself is blocked by ESTree's AST design for the syntax), and so you will need to do this transformation in a preprocessor before Svelte runs.

**Comment by Conduitry** [comment]
Oh, if the syntax is only present in an external .js file, that should be unrelated to Svelte not handling it - and probably indicates you need to configure Babel to transpile it, because Rollup is also probably not going to be able to handle it.

**Comment by thinkloop** [comment]
@iOiurson the problem might be `legacy && babel` - the babel options don't run if `legacy` is `false`. If you remove `legacy` it will run the babel options.
