### ISSUE TITLE
Server Crash at build, while running dev (rollup)

### ISSUE THREAD

**Issue by Mlocik97-issues** [sveltejs/sapper#1132]
```
  "scripts": {
    "dev": "sapper dev",
    "build": "sapper build --legacy",
    "export": "sapper export --legacy",
    "start": "node __sapper__/build"
  },
  "dependencies": {
    "body-parser": "^1.19.0",
    "compression": "^1.7.1",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "nano": "^8.1.0",
    "polka": "next",
    "sirv": "^0.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "@rollup/plugin-commonjs": "^11.0.0",
    "@rollup/plugin-node-resolve": "^7.0.0",
    "@rollup/plugin-replace": "^2.2.0",
    "npm-run-all": "^4.1.5",
    "rollup": "^1.20.0",
    "rollup-plugin-babel": "^4.0.2",
    "rollup-plugin-svelte": "^5.0.1",
    "rollup-plugin-terser": "^4.0.4",
    "sapper": "^0.27.11",
    "svelte": "^3.0.0"
  }
```

```
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open '__sapper__/build/build.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at get_page_handler (/mnt/3ED872D5D8728B43/project/__sapper__/dev/server/server.js:2559:65)
    at middleware (/mnt/3ED872D5D8728B43/project/__sapper__/dev/server/server.js:2987:3)
    at Object.<anonymous> (/mnt/3ED872D5D8728B43/project/__sapper__/dev/server/server.js:3074:2)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '__sapper__/build/build.json'
}
> Server crashed

```

When I run dev, and then I run build, server in dev mode crash. Why is "dev" instance looking to build folder instead dev?

**Comment by antony** [comment]
@Mlocik97-issues can you follow the issue template and share a reproduction with us please, this issue doesn't contain any useful information.
