### ISSUE TITLE
[question] Nice way to load and use static JSON data in page?

### ISSUE THREAD

**Issue by ikeamanual** [sveltejs/sapper#128]
Hi,
What would be the recommended clean way to:
1. load a a static JSON data file at startup
2. use it in the sapper post sample:
```
<div class='content'>
  {{{post.html}}}
</div>
```

**Comment by thgh** [comment]
Webpack can load and parse json files.

https://svelte.technology/repl?version=1.55.0&gist=484a7c9d407af716ca0aba2539f26585

**Comment by Rich-Harris** [comment]
Closing this, as it's supported idiomatically in webpack. You just need to ensure that `.json` is included in `resolve.extensions` in both [client](https://github.com/sveltejs/sapper-template/blob/9cfad2d8492a0d537b6d97d9bd72751d7e949d81/webpack/client.config.js#L11) and [server](https://github.com/sveltejs/sapper-template/blob/9cfad2d8492a0d537b6d97d9bd72751d7e949d81/webpack/server.config.js#L9) webpack configs.

**Comment by chovy** [comment]
How can I resolve .json files with rollup?

`const items = require("./_pocket-scarves.json");`

```
To preserve the export signature of the entry module "src/client.js", an empty facade chunk was created. This often happens when creating a bundle for a web app where chunks are placed in script tags and exports are ignored. In this case it is recommended to set "preserveEntrySignatures: false" to avoid this and reduce the number of chunks. Otherwise if this is intentional, set "preserveEntrySignatures: 'strict'" explicitly to silence this warning.
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module './_pocket-scarves.json'
Require stack:
- /home/ettinger/www/pocketscarves.com/ui/__sapper__/dev/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/ettinger/www/pocketscarves.com/ui/__sapper__/dev/server/server.js:24:15)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ettinger/www/pocketscarves.com/ui/__sapper__/dev/server/server.js'
  ]
```

**Comment by antony** [comment]
@chovy discord is a better place for questions like this, but `@rollup/plugin-json` is your one-stop-shop for loading `json` files
