### ISSUE TITLE
Sapper reports generic error if bundler config is missing entirely.

### ISSUE THREAD

**Issue by Kruhlmann** [sveltejs/sapper#1376]
**Describe the bug**

The `validate_config` function does not report an undefined bundler config as custom error. Instead it throws the following error:

```
Cannot read property 'client' of undefined
TypeError: Cannot read property 'client' of undefined
    at validate_config (/mnt/hdd/home/doc/src/github.com/kruhlmann/kruhlmann.dev/node_modules/sapper/dist/create_manifest_data.js:1237:14)
    at Object.create_compilers (/mnt/hdd/home/doc/src/github.com/kruhlmann/kruhlmann.dev/node_modules/sapper/dist/create_manifest_data.js:1205:3)
    at async build (/mnt/hdd/home/doc/src/github.com/kruhlmann/kruhlmann.dev/node_modules/sapper/dist/build.js:81:44)
    at async _build (/mnt/hdd/home/doc/src/github.com/kruhlmann/kruhlmann.dev/node_modules/sapper/dist/cli.js:698:2)
    at async /mnt/hdd/home/doc/src/github.com/kruhlmann/kruhlmann.dev/node_modules/sapper/dist/cli.js:584:4
```

Here is the conditional:

https://github.com/sveltejs/sapper/blob/52f40f9e63dab19ad11f5073b2446b2632c85179/src/core/create_compilers/index.ts#L58-L62

**To Reproduce**
Create a rollup config, which exports undefined.

**Expected behavior**
The custom error should also be thrown when a config is missing entirely, as it is also useful in that scenario.

**Information about your Sapper Installation:**

```
  System:
    OS: Linux 5.7 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 3.68 GB / 15.57 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - /usr/bin/npm
  npmPackages:
    rollup: ^2.22.2 => 2.23.1 
    sapper: ^0.28.0 => 0.28.0 
    svelte: ^3.24.0 => 3.24.1 
```

**Severity**
Borderline insignificant

**Comment by portfolioris** [comment]
I just ran into this after upgrading all my node_modules. I fixed this by changing `module.exports = {` into `export default {` in `rollup.config.js`. Maybe it helps you?

I changed this myself once before to statisfy eslint.
