### ISSUE TITLE
Sapper throws exception: 'Cannot read property 'parts' of undefined'

### ISSUE THREAD

**Issue by zwergius** [sveltejs/sapper#1390]
**Describe the bug**
After updating sapper I'm seeing the following error running the dev server
(node:2198) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parts' of undefined

**Logs**
(node:2198) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parts' of undefined
    at handle_page (/Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:9022:23)
    at Array.find_route (/Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:9306:4)
    at nth_handler (/Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:9427:14)
    at /Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:9427:31
    at Array.find_route (/Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:6902:3)
    at nth_handler (/Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:9427:14)
    at /Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:9427:31
    at Array.<anonymous> (/Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:9482:4)
    at nth_handler (/Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:9427:14)
    at /Users/dr_zwerge/Git/el-danes/__sapper__/dev/server/server-815112f1.js:9427:31
(node:2198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**To Reproduce**
Open in localhost

I updated all of the following packages:
Package                          Current   Wanted  Latest  Location
@babel/core                       7.10.5   7.11.1  7.11.1  el-danes
@babel/plugin-transform-runtime   7.10.5   7.11.0  7.11.0  el-danes
@babel/preset-env                 7.10.4   7.11.0  7.11.0  el-danes
@babel/runtime                    7.10.5   7.11.2  7.11.2  el-danes
autoprefixer                       9.8.5    9.8.6   9.8.6  el-danes
eslint                             7.5.0    7.6.0   7.6.0  el-danes
rollup                            2.23.0   2.23.1  2.23.1  el-danes
rollup-plugin-terser               6.1.0    6.1.0   7.0.0  el-danes
sapper                           0.27.16  0.27.16  0.28.0  el-danes
sirv                               1.0.1    1.0.5   1.0.5  el-danes
svelte                            3.24.0   3.24.1  3.24.1  el-danes
svelte-preprocess                  4.0.8   4.0.10  4.0.10  el-danes

**Comment by Conduitry** [comment]
Did you also follow the other steps laid out in https://sapper.svelte.dev/migrating ? We need a reproduction.

**Comment by zwergius** [comment]
Hi again,

So finally got around to having another look at this - seems this issue was made visible by this update only, cause was elsewhere..

**Comment by zwergius** [comment]
Hi again again,

So this issue kept re-appearing and I've finally found the issue.

So this project was setup with svelte-i18n, but modified to use url for setting locale => /en /es /da

So I put all my routes inside routes/[lang]/index.svelte

That meant that I did not have a routes/index.svelte <== Adding this file fixed this error and made my project create service-worker-index.html (which was missing) when exporting...

I'm reopening this issue and I'll let you maintainers decide if it's a bug or a feature ;)

**Comment by Jayphen** [comment]
I had precisely the same problem, with the same solution. Thanks @zwergius.

**Comment by Conduitry** [comment]
This should be fixed in 0.28.10.
