### ISSUE TITLE
Hit brick wall when adding svelte-preprocess to minimal sapper example

### ISSUE THREAD

**Issue by callumlocke** [sveltejs/sapper#1396]
**Describe the bug**
New to Svelte/Sapper. Tried following the svelte-preprocess "Getting Started" docs on a clone of the sapper-template, and the minimal template app fails with this cryptic error:

```
(node:13833) UnhandledPromiseRejectionWarning: Error: Could not find chunk that owns index.svelte
```

It comes from this code in Sapper's `create_manifest_data.js`:

```js
		if (!chunk) {
			// this should never happen!
			throw new Error(`Could not find chunk that owns ${component.file}`);
		}
```

I'm literally just trying to get TypeScript working with the default sapper template, following instructions precisely and doing nothing custom, and I hit a dead end. Using latest versions of everything (started from scratch this morning).

**To Reproduce**
1. Create a sapper app from the template: `npx degit "sveltejs/sapper-template#rollup" my-app`
    - Install deps and run `npm run dev` – it launches fine.
2. Follow the svelte-preprocess [Getting Started](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/getting-started.md) guide, just up to the end of Step 3 (Configuring Preprocessors).
    - Only difference: change `sourceMap: !dev` to `sourceMap: production`, as this is what the sapper-template's rollup config uses.

**Expected behavior**
I should be able to run `npm run dev` as before.

**Actual behavior**
Running `npm run dev` fails with an unhandled rejection.

Note I have not even attempted to modify any components yet to actually _use_ TypeScript etc. - I haven't added any `lang` attributes or set default languages for svelte-preprocess.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

```
$ sapper dev
✗ client
@rollup/plugin-typescript: Couldn't process compiler options
(node:13833) UnhandledPromiseRejectionWarning: Error: Could not find chunk that owns index.svelte
    at /Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:570:10
    at Array.forEach (<anonymous>)
    at extract_css (/Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:564:13)
    at RollupResult.to_json (/Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:752:9)
    at handle_result (/Users/callum/code/my-app/node_modules/sapper/dist/dev.js:335:28)
    at /Users/callum/code/my-app/node_modules/sapper/dist/dev.js:429:5
    at WatchEmitter.<anonymous> (/Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:884:6)
    at WatchEmitter.emit (events.js:315:20)
    at Watcher.emit (/Users/callum/code/my-app/node_modules/rollup/dist/shared/watch.js:611:22)
    at Watcher.run (/Users/callum/code/my-app/node_modules/rollup/dist/shared/watch.js:649:18)
(node:13833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13833) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tslib/tslib.es6.js' from '/Users/callum/code/my-app/node_modules/@rollup/plugin-typescript/dist'
    at /Users/callum/code/my-app/node_modules/resolve/lib/async.js:115:35
    at processDirs (/Users/callum/code/my-app/node_modules/resolve/lib/async.js:268:39)
    at isdir (/Users/callum/code/my-app/node_modules/resolve/lib/async.js:275:32)
    at /Users/callum/code/my-app/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (fs.js:171:21)
(node:13833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

</details>

**Information about your project:**

- Your browser and the version: N/A

- Your operating system: macOS 10.15 Beta

- `svelte-preprocess` version: 4.0.10

- Rollup

**Comment by callumlocke** [comment]
Update: I tried commenting out the `typescript()` plugin in my rollup config, and the dev server now launches fine. And, encouragingly, I tried writing some SCSS in a component, and it seems to work correctly. So the problem seems to be specific to using the TypeScript rollup plugin.

**Comment by benmccann** [comment]
Here's an example project: https://github.com/babichjacob/sapper-typescript-graphql-template. It seems to work, so I'm not quite sure what issue you're having

**Comment by pngwn** [comment]
@callumlocke if you could provide your config we can check to see if anything is amiss.

**Comment by callumlocke** [comment]
@pngwn which config?

**Comment by pngwn** [comment]
Your rollup config.

**Comment by callumlocke** [comment]
```js
import resolve from '@rollup/plugin-node-resolve'
import replace from '@rollup/plugin-replace'
import commonjs from '@rollup/plugin-commonjs'
import svelte from 'rollup-plugin-svelte'
import sveltePreprocess from 'svelte-preprocess'
import typescript from '@rollup/plugin-typescript'
import babel from '@rollup/plugin-babel'
import { terser } from 'rollup-plugin-terser'
import config from 'sapper/config/rollup.js'
import pkg from './package.json'

const mode = process.env.NODE_ENV
const dev = mode === 'development'
const legacy = !!process.env.SAPPER_LEGACY_BUILD

const onwarn = (warning, onwarn) =>
  (warning.code === 'MISSING_EXPORT' && /'preload'/.test(warning.message)) ||
  (warning.code === 'CIRCULAR_DEPENDENCY' &&
    /[/\\]@sapper[/\\]/.test(warning.message)) ||
  onwarn(warning)

export default {
  client: {
    input: config.client.input(),
    output: config.client.output(),
    plugins: [
      // teach rollup how to handle typescript imports
      typescript({ sourceMap: dev }),

      replace({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),
      svelte({
        preprocess: sveltePreprocess({
          sourceMap: dev,
          postcss: {
            plugins: [require('autoprefixer')()],
          },
        }),
        dev,
        hydratable: true,
        emitCss: true,
        preprocess: sveltePreprocess({
          sourceMap: dev,
        }),
      }),
      resolve({
        browser: true,
        dedupe: ['svelte'],
      }),
      commonjs(),

      legacy &&
        babel({
          extensions: ['.js', '.mjs', '.html', '.svelte'],
          babelHelpers: 'runtime',
          exclude: ['node_modules/@babel/**'],
          presets: [
            [
              '@babel/preset-env',
              {
                targets: '> 0.25%, not dead',
              },
            ],
          ],
          plugins: [
            '@babel/plugin-syntax-dynamic-import',
            [
              '@babel/plugin-transform-runtime',
              {
                useESModules: true,
              },
            ],
          ],
        }),

      !dev &&
        terser({
          module: true,
        }),
    ],

    preserveEntrySignatures: false,
    onwarn,
  },

  server: {
    input: config.server.input(),
    output: config.server.output(),
    plugins: [
      replace({
        'process.browser': false,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),
      svelte({
        generate: 'ssr',
        hydratable: true,
        dev,
      }),
      resolve({
        dedupe: ['svelte'],
      }),
      commonjs(),
    ],
    external: Object.keys(pkg.dependencies).concat(
      require('module').builtinModules
    ),

    preserveEntrySignatures: 'strict',
    onwarn,
  },

  serviceworker: {
    input: config.serviceworker.input(),
    output: config.serviceworker.output(),
    plugins: [
      resolve(),
      replace({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),
      commonjs(),
      !dev && terser(),
    ],

    preserveEntrySignatures: false,
    onwarn,
  },
}
```

The above is literally just the [official sapper-template#rollup config](https://github.com/sveltejs/sapper-template/blob/rollup/rollup.config.js), plus a few lines added according to the [svelte-preprocess Geting Started](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/getting-started.md) guide.

If I comment out the `typescript({ sourceMap: dev })` line, it works.

**Comment by pngwn** [comment]
You seem to have two `preprocess` keys in the client config and none in the server config.

**Comment by pngwn** [comment]
This actually may be because your extra preprocess config is overwriting your postcss config which is causing parsing errors.

**Comment by pngwn** [comment]
You will also need to put that typescript plugin in your server config as well.

**Comment by callumlocke** [comment]
OK, I've removed that duplicate key, and also added the typescript plugin to the server config, and put the same `preprocess` key in the server config:

```js
import resolve from '@rollup/plugin-node-resolve';
import replace from '@rollup/plugin-replace';
import commonjs from '@rollup/plugin-commonjs';
import svelte from 'rollup-plugin-svelte';
import sveltePreprocess from 'svelte-preprocess';
import typescript from '@rollup/plugin-typescript';
import babel from '@rollup/plugin-babel';
import { terser } from 'rollup-plugin-terser';
import config from 'sapper/config/rollup.js';
import pkg from './package.json';

const mode = process.env.NODE_ENV;
const dev = mode === 'development';
const legacy = !!process.env.SAPPER_LEGACY_BUILD;

const onwarn = (warning, onwarn) =>
	(warning.code === 'MISSING_EXPORT' && /'preload'/.test(warning.message)) ||
	(warning.code === 'CIRCULAR_DEPENDENCY' && /[/\\]@sapper[/\\]/.test(warning.message)) ||
	onwarn(warning);

export default {
	client: {
		input: config.client.input(),
		output: config.client.output(),
		plugins: [
			// teach rollup how to handle typescript imports
			typescript({ sourceMap: dev }),

			replace({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svelte({
				preprocess: sveltePreprocess({
					sourceMap: dev,
					postcss: {
						plugins: [require('autoprefixer')()]
					}
				}),
				dev,
				hydratable: true,
				emitCss: true
			}),
			resolve({
				browser: true,
				dedupe: ['svelte']
			}),
			commonjs(),

			legacy && babel({
				extensions: ['.js', '.mjs', '.html', '.svelte'],
				babelHelpers: 'runtime',
				exclude: ['node_modules/@babel/**'],
				presets: [
					['@babel/preset-env', {
						targets: '> 0.25%, not dead'
					}]
				],
				plugins: [
					'@babel/plugin-syntax-dynamic-import',
					['@babel/plugin-transform-runtime', {
						useESModules: true
					}]
				]
			}),

			!dev && terser({
				module: true
			})
		],

		preserveEntrySignatures: false,
		onwarn,
	},

	server: {
		input: config.server.input(),
		output: config.server.output(),
		plugins: [
			// teach rollup how to handle typescript imports
			typescript({ sourceMap: dev }),

			replace({
				'process.browser': false,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svelte({
				preprocess: sveltePreprocess({
					sourceMap: dev,
					postcss: {
						plugins: [require('autoprefixer')()]
					}
				}),

				generate: 'ssr',
				hydratable: true,
				dev
			}),
			resolve({
				dedupe: ['svelte']
			}),
			commonjs()
		],
		external: Object.keys(pkg.dependencies).concat(require('module').builtinModules),

		preserveEntrySignatures: 'strict',
		onwarn,
	},

	serviceworker: {
		input: config.serviceworker.input(),
		output: config.serviceworker.output(),
		plugins: [
			resolve(),
			replace({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			commonjs(),
			!dev && terser()
		],

		preserveEntrySignatures: false,
		onwarn,
	}
};
```

But the problem remains. The only difference AFAICT is the stack trace now shows a 'server' error too:

```
❯ yarn dev
yarn run v1.22.4
$ sapper dev
✗ server
@rollup/plugin-typescript: Couldn't process compiler options
✗ client
@rollup/plugin-typescript: Couldn't process compiler options
(node:31772) UnhandledPromiseRejectionWarning: Error: Could not find chunk that owns index.svelte
    at /Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:570:10
    at Array.forEach (<anonymous>)
    at extract_css (/Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:564:13)
    at RollupResult.to_json (/Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:752:9)
    at handle_result (/Users/callum/code/my-app/node_modules/sapper/dist/dev.js:335:28)
    at /Users/callum/code/my-app/node_modules/sapper/dist/dev.js:429:5
    at WatchEmitter.<anonymous> (/Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:884:6)
    at WatchEmitter.emit (events.js:315:20)
    at Watcher.emit (/Users/callum/code/my-app/node_modules/rollup/dist/shared/watch.js:611:22)
    at Watcher.run (/Users/callum/code/my-app/node_modules/rollup/dist/shared/watch.js:649:18)
(node:31772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31772) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tslib/tslib.es6.js' from '/Users/callum/code/my-app/node_modules/@rollup/plugin-typescript/dist'
    at /Users/callum/code/my-app/node_modules/resolve/lib/async.js:115:35
    at processDirs (/Users/callum/code/my-app/node_modules/resolve/lib/async.js:268:39)
    at isdir (/Users/callum/code/my-app/node_modules/resolve/lib/async.js:275:32)
    at /Users/callum/code/my-app/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (fs.js:171:21)
(node:31772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:31772) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tslib/tslib.es6.js' from '/Users/callum/code/my-app/node_modules/@rollup/plugin-typescript/dist'
    at /Users/callum/code/my-app/node_modules/resolve/lib/async.js:115:35
    at processDirs (/Users/callum/code/my-app/node_modules/resolve/lib/async.js:268:39)
    at isdir (/Users/callum/code/my-app/node_modules/resolve/lib/async.js:275:32)
    at /Users/callum/code/my-app/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (fs.js:171:21)
(node:31772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
^C
```

I also just noticed this part in the stack trace:


```
Error: Cannot find module 'tslib/tslib.es6.js' from '/Users/callum/code/my-app/node_modules/@rollup/plugin-typescript/dist'
```

...so I tried `rm -rf node_modules && yarn`, but the problem remains.

**Comment by callumlocke** [comment]
(Also just tried `rm -rf node_modules && npm i`, in case it's a problem with how yarn installs things, but I just get the same errors when I do `npm run dev`.)

**Comment by pngwn** [comment]
Try installing tslib. `yarn add --dev tslib`

**Comment by callumlocke** [comment]
OK, installed tslib, and the stack trace no longer complains about that. But it still has the `Could not find chunk that owns index.svelte` error:

```
> sapper dev

✗ server
@rollup/plugin-typescript: Couldn't process compiler options
✗ client
@rollup/plugin-typescript: Couldn't process compiler options
(node:33203) UnhandledPromiseRejectionWarning: Error: Could not find chunk that owns index.svelte
    at /Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:570:10
    at Array.forEach (<anonymous>)
    at extract_css (/Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:564:13)
    at RollupResult.to_json (/Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:752:9)
    at handle_result (/Users/callum/code/my-app/node_modules/sapper/dist/dev.js:335:28)
    at /Users/callum/code/my-app/node_modules/sapper/dist/dev.js:429:5
    at WatchEmitter.<anonymous> (/Users/callum/code/my-app/node_modules/sapper/dist/create_manifest_data.js:884:6)
    at WatchEmitter.emit (events.js:315:20)
    at Watcher.emit (/Users/callum/code/my-app/node_modules/rollup/dist/shared/watch.js:611:22)
    at Watcher.run (/Users/callum/code/my-app/node_modules/rollup/dist/shared/watch.js:649:18)
(node:33203) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33203) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

**Comment by benmccann** [comment]
The "Could not find chunk that owns index.svelte" seems like a duplicate of https://github.com/sveltejs/sapper/issues/1334 though they're not using Typescript in that example. Do you get the error without using Typescript? If you message me on Discord (my username is the same there), I can help you debug in realtime

**Comment by benmccann** [comment]
I talked to @callumlocke on Discord and we found that `renderChunk` is never being called for him:

https://github.com/sveltejs/sapper/blob/24e7dd1138e1c219165346e5d25a298680e3796b/src/core/create_compilers/RollupCompiler.ts#L38

At this point, it's pretty clear it's not a bug in Sapper because Sapper's code is never being called. It's got to be some issue with Rollup or one of its plugins or configuration, but I'm less familiar with those code bases, so not sure where to go from here.

**Comment by babichjacob** [comment]
If this is useless, I'm sorry:

First, I always have `@rollup/plugin-typescript` listed as a plugin *after* CommonJS and more importantly after Svelte.

Another thing—one reason `Couldn't process compiler options` happens, if I remember correctly, is if there are no `.ts` files in your `src` directory. Try making a purposeless server route like [`src/routes/example.ts`](https://github.com/babichjacob/sapper-typescript-graphql-template/blob/main/src/routes/example.ts) with this content:
```ts
import type { Request as ExpressRequest, Response as ExpressResponse } from "express";

export const get = async (req: ExpressRequest, res: ExpressResponse): Promise<void> => {
	res.end("you made a get request");
};

export const post = async (req: ExpressRequest, res: ExpressResponse): Promise<void> => {
	res.end("you made a post request");
};
```
(if you need to install `express` and `@types/express` for this to work, do so — this probably doesn't require switching from Polka to Express in `server.ts`, but if it does, then try that too).

**Comment by callumlocke** [comment]
@babichjacob thanks for the suggestions, but I still get the same error. I had already moved the typescript plugin to after commonjs. And I just tried adding that `example.ts` route as you suggested, but still no luck.

**Comment by benmccann** [comment]
Try adding this file:

https://github.com/babichjacob/sapper-typescript-graphql-template/blob/main/types/%40sapper/index.d.ts

And putting it in your `tsconfig.json`:

https://github.com/babichjacob/sapper-typescript-graphql-template/blob/main/tsconfig.json#L19

**Comment by babichjacob** [comment]
I actually, just now, got this exact error after upgrading to 0.28 (which did not cause the error, by the way), making some changes (which exact one caused it, I don't know), then fixed it by resolving all the TypeScript errors as they were revealed to me in the console.

(That mainly meant replacing all the type-only imports with `import type`).

**Comment by maiksch** [comment]
I also had the problem ```(node:23532) UnhandledPromiseRejectionWarning: Error: Could not find chunk that owns index.svelte``` on a small project that I migrated to Typescript. The cause was a ```"module": "CommonJS"``` in the ```tsconfig.json``` that I added and forgot about. It worked after I removed that.

**Comment by kairauer** [comment]
I'm having the exact same issue after creating a new Sapper project based on the default template + following the steps described in the "Svelte <3 TypeScript" article.
I was able to solve the issue by changing the following:

- Change src/client.js and src/server.js to .ts files
- Create typings/@sapper directory in the root directory and add a index.d.ts file with the following content:
```javascript
declare module "@sapper/app";
declare module "@sapper/server";
declare module "@sapper/service-worker";
```
- Add types to tsconfig.json - my tsconfig.json:
```json
{
    "extends": "@tsconfig/svelte/tsconfig.json",
    "include": ["src/**/*", "src/node_modules"],
    "exclude": ["node_modules/*", "__sapper__/*", "public/*"],
    "compilerOptions": {
        "types": ["svelte", "node", "@sapper"],
        "typeRoots": ["typings"]
    }
}
```
- Place `typescript({ sourceMap: dev })` in both client and server sections below `commonjs()` - see rollup.config.js below
- Tell rollup to look for .ts files instead of .js files - see rollup.config.js below
```javascript
import resolve from "@rollup/plugin-node-resolve";
import replace from "@rollup/plugin-replace";
import commonjs from "@rollup/plugin-commonjs";
import svelte from "rollup-plugin-svelte";
import babel from "@rollup/plugin-babel";
import { terser } from "rollup-plugin-terser";
import config from "sapper/config/rollup.js";
import pkg from "./package.json";
import autoPreprocess from "svelte-preprocess";
import typescript from "@rollup/plugin-typescript";

const mode = process.env.NODE_ENV;
const dev = mode === "development";
const legacy = !!process.env.SAPPER_LEGACY_BUILD;
const onwarn = (warning, onwarn) =>
    (warning.code === "MISSING_EXPORT" && /'preload'/.test(warning.message)) ||
    (warning.code === "CIRCULAR_DEPENDENCY" && /[/\\]@sapper[/\\]/.test(warning.message)) ||
    onwarn(warning);

export default {
    client: {
        input: config.client.input().replace(/\.js$/, ".ts"),
        output: config.client.output(),
        plugins: [
            replace({
                "process.browser": true,
                "process.env.NODE_ENV": JSON.stringify(mode),
            }),
            svelte({
                dev,
                hydratable: true,
                emitCss: true,
                preprocess: autoPreprocess(),
            }),
            resolve({
                browser: true,
                dedupe: ["svelte"],
            }),
            commonjs(),
            typescript({ sourceMap: dev }),
            legacy &&
                babel({
                    extensions: [".js", ".mjs", ".html", ".svelte"],
                    babelHelpers: "runtime",
                    exclude: ["node_modules/@babel/**"],
                    presets: [
                        [
                            "@babel/preset-env",
                            {
                                targets: "> 0.25%, not dead",
                            },
                        ],
                    ],
                    plugins: [
                        "@babel/plugin-syntax-dynamic-import",
                        [
                            "@babel/plugin-transform-runtime",
                            {
                                useESModules: true,
                            },
                        ],
                    ],
                }),
            !dev &&
                terser({
                    module: true,
                }),
        ],
        preserveEntrySignatures: false,
        onwarn,
    },
    server: {
        input: config.server.input().server.replace(/\.js$/, ".ts"),
        output: config.server.output(),
        plugins: [
            replace({
                "process.browser": false,
                "process.env.NODE_ENV": JSON.stringify(mode),
            }),
            svelte({
                generate: "ssr",
                hydratable: true,
                dev,
            }),
            resolve({
                dedupe: ["svelte"],
            }),
            commonjs(),
            typescript({ sourceMap: dev }),
        ],
        external: Object.keys(pkg.dependencies).concat(require("module").builtinModules),
        preserveEntrySignatures: "strict",
        onwarn,
    },
    serviceworker: {
        //..... nothing changed here
    },
};
```
Everything is working now fine as far as I can see.
