### ISSUE TITLE
ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by mehdiraized** [sveltejs/sapper#1451]
**Describe the bug**
After Start Project i have error

**Logs**
```
> ELOOP: too many symbolic links encountered, stat '/root/project-frontend/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static'
Error: ELOOP: too many symbolic links encountered, stat '/root/project-frontend/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static/static'
    at Object.statSync (fs.js:1016:3)
    at /root/project-frontend/node_modules/sapper/dist/index.js:36:10
    at Array.forEach (<anonymous>)
    at walk (/root/project-frontend/node_modules/sapper/dist/index.js:34:22)
    at /root/project-frontend/node_modules/sapper/dist/index.js:37:4
    at Array.forEach (<anonymous>)
    at walk (/root/project-frontend/node_modules/sapper/dist/index.js:34:22)
    at /root/project-frontend/node_modules/sapper/dist/index.js:37:4
    at Array.forEach (<anonymous>)
    at walk (/root/project-frontend/node_modules/sapper/dist/index.js:34:22)
```

**Information about your Sapper Installation:**

- The output of `npx envinfo --system --npmPackages svelte,sapper,rollup,webpack --binaries --browsers`
```
  System:
    OS: macOS 11.0
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 88.63 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.5 - ~/Desktop/Project/project-front/node_modules/.bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 83.1.10.97
    Chrome: 84.0.4147.135
    Firefox: 78.0.2
    Firefox Developer Edition: 79.0
    Safari: 14.0
    Safari Technology Preview: 14.0
  npmPackages:
    rollup: ^2.26.6 => 2.26.6
    sapper: ^0.28.2 => 0.28.2
    svelte: ^3.24.1 => 3.24.1
```

- Your hosting environment (i.e. Local, GCP/AWS/Azure, Vercel/Begin, etc...)
```
Local
```

**Comment by Conduitry** [comment]
This sounds like an environmental issue to me. I have no idea why `static` would be a symlink to itself, which is what looks like is happening.

GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
