### ISSUE TITLE
Sapper Optional Chaining operator for Webpack

### ISSUE THREAD

**Issue by thousandsofraccoons** [sveltejs/sapper#1615]
**Describe the bug**
Optional Chaining operator doesn't work with Webpack

**Logs**
```bash
$ npm run dev

> TODO@0.0.1 dev C:\Users\test\sapper-webpack-typescript
> sapper dev

✗ server
src/routes/_layout.svelte 13:23
Module parse failed: Unexpected token
File was processed with these loaders:
 * ./node_modules/svelte-loader/index.js
You may need an additional loader to handle the result of these loaders.
| const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
|       let { segment } = $$props;
>       const test = document?.querySelector("body");
|       if ($$props.segment === void 0 && $$bindings.segment && segment !== void 0) $$bindings.segment(segment);
|       $$result.css.add(css);

src\node_modules\@sapper\internal\shared.mjs changed. rebuilding...
✗ client
src/routes/_layout.svelte 131:23
Module parse failed: Unexpected token
File was processed with these loaders:
 * ./node_modules/svelte-loader/index.js
You may need an additional loader to handle the result of these loaders.
|       validate_slots("Layout", slots, ['default']);
|       let { segment } = $$props;
>       const test = document?.querySelector("body");
|       const writable_props = ["segment"];
|

src\node_modules\@sapper\app.mjs changed. rebuilding...
✔ service worker (31ms)
webpack:///./src/routes/_layout.svelte?:1
throw new Error("Module parse failed: Unexpected token (13:23)\nFile was processed with these loaders:\n * ./node_modules/svelte-loader/index.js\nYou may need an additional loader to handle the result of these loaders.\n| const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {\n| \tlet { segment } = $$props;\n> \tconst test = document?.querySelector(\"body\");\n| \tif ($$props.segment === void 0 && $$bindings.segment && segment !== void 0) $$bindings.segment(segment);\n| \t$$result.css.add(css);");
^

Error: Module parse failed: Unexpected token (13:23)
File was processed with these loaders:
 * ./node_modules/svelte-loader/index.js
You may need an additional loader to handle the result of these loaders.
| const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
|       let { segment } = $$props;
>       const test = document?.querySelector("body");
|       if ($$props.segment === void 0 && $$bindings.segment && segment !== void 0) $$bindings.segment(segment);
|       $$result.css.add(css);
    at eval (webpack:///./src/routes/_layout.svelte?:1:7)
    at Object../src/routes/_layout.svelte (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:205:1)
    at __webpack_require__ (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/internal/manifest-server.mjs?:12:79)
    at Module../src/node_modules/@sapper/internal/manifest-server.mjs (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:146:1)
    at __webpack_require__ (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/server.mjs?:7:83)
    at Module../src/node_modules/@sapper/server.mjs (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:170:1)
    at __webpack_require__ (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/server.js?:8:72)
> Server crashed
✗ server
src/routes/_layout.svelte 13:23
Module parse failed: Unexpected token
File was processed with these loaders:
 * ./node_modules/svelte-loader/index.js
You may need an additional loader to handle the result of these loaders.
| const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
|       let { segment } = $$props;
>       const test = document?.querySelector("body");
|       if ($$props.segment === void 0 && $$bindings.segment && segment !== void 0) $$bindings.segment(segment);
|       $$result.css.add(css);
✗ client
src/routes/_layout.svelte 131:23
Module parse failed: Unexpected token
File was processed with these loaders:
 * ./node_modules/svelte-loader/index.js
You may need an additional loader to handle the result of these loaders.
|       validate_slots("Layout", slots, ['default']);
|       let { segment } = $$props;
>       const test = document?.querySelector("body");
|       const writable_props = ["segment"];
|
webpack:///./src/routes/_layout.svelte?:1
throw new Error("Module parse failed: Unexpected token (13:23)\nFile was processed with these loaders:\n * ./node_modules/svelte-loader/index.js\nYou may need an additional loader to handle the result of these loaders.\n| const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {\n| \tlet { segment } = $$props;\n> \tconst test = document?.querySelector(\"body\");\n| \tif ($$props.segment === void 0 && $$bindings.segment && segment !== void 0) $$bindings.segment(segment);\n| \t$$result.css.add(css);");
^

Error: Module parse failed: Unexpected token (13:23)
File was processed with these loaders:
 * ./node_modules/svelte-loader/index.js
You may need an additional loader to handle the result of these loaders.
| const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
|       let { segment } = $$props;
>       const test = document?.querySelector("body");
|       if ($$props.segment === void 0 && $$bindings.segment && segment !== void 0) $$bindings.segment(segment);
|       $$result.css.add(css);
    at eval (webpack:///./src/routes/_layout.svelte?:1:7)
    at Object../src/routes/_layout.svelte (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:205:1)
    at __webpack_require__ (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/internal/manifest-server.mjs?:12:79)
    at Module../src/node_modules/@sapper/internal/manifest-server.mjs (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:146:1)
    at __webpack_require__ (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/server.mjs?:7:83)
    at Module../src/node_modules/@sapper/server.mjs (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:170:1)
    at __webpack_require__ (C:\Users\test\sapper-webpack-typescript\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/server.js?:8:72)
> Server crashed
✔ service worker (15ms)
```

**To Reproduce**
Install latest Sapper and just add `test = document?.querySelector('body')` anywhere.

**Expected behavior**
Compiled project.

**Stacktraces**

**Information about your Sapper Installation:**
Just `npx degit "sveltejs/sapper-template#webpack" my-app`  with current latest version.

- The output of `npx envinfo --system --npmPackages svelte,sapper,rollup,webpack --binaries --browsers`
```bash
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 6.29 GB / 15.87 GB
  Binaries:
    Node: 14.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.51)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    sapper: ^0.28.0 => 0.28.10
    svelte: ^3.28.0 => 3.29.4
    webpack: ^4.7.0 => 4.44.2
```
- Your browser
Brave

- Your hosting environment (i.e. Local, GCP/AWS/Azure, Vercel/Begin, etc...)
Localhost

- If it is an exported (`npm run export`) or dynamic application

**Severity**
I could use workaround, but I'm not sure how to setup Babel to make it work.

**Additional context**

**Comment by Conduitry** [comment]
iirc webpack 4 does not support that syntax, and svelte-loader doesn't yet support webpack 5.
