### ISSUE TITLE
Requesting /client/ as directory is not internal server error (500), it is just simple not found (404)

### ISSUE THREAD

**Issue by hillar** [sveltejs/sapper#1733]
https://github.com/sveltejs/sapper/blob/67cb6be0befd087bafb4491772d21aad6ea4e75f/runtime/src/server/middleware/index.ts#L130

**Comment by hillar** [comment]
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at read (test-sapper/server/__sapper__/dev/server/server.js:37133:52)
    at Array.<anonymous> (test-sapper/server/__sapper__/dev/server/server.js:37140:30)
    at nth_handler (test-sapper/server/__sapper__/dev/server/server.js:37107:20)
    at test-sapper/server/__sapper__/dev/server/server.js:37107:37
    at Array.<anonymous> (test-sapper/server/__sapper__/dev/server/server.js:37083:13)
    at nth_handler (test-sapper/server/__sapper__/dev/server/server.js:37107:20)
    at Array.<anonymous> (test-sapper/server/__sapper__/dev/server/server.js:37110:31) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```
