### ISSUE TITLE
Exception thrown with `routes/[foo]/[bar].html` on Windows

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/sapper#212]
This seems to be happening on Windows only, not Linux or (I've been told) macOS.

A route called something like `routes/[foo]/[bar].html` causes an error to be thrown from within snapdragon:

```
C:\...\node_modules\snapdragon\lib\parser.js:473
        throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');
        ^

Error: no parsers registered for: "]"
    at parse (C:\...\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (C:\...\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (C:\...\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (C:\...\node_modules\braces\lib\braces.js:42:45)
    at Braces.parse (C:\...\node_modules\braces\lib\braces.js:68:26)
    at Braces.expand (C:\...\node_modules\braces\lib\braces.js:89:18)
    at create (C:\...\node_modules\braces\index.js:143:15)
    at memoize (C:\...\node_modules\braces\index.js:295:13)
    at Function.braces.create (C:\...\node_modules\braces\index.js:162:10)
    at Function.braces.expand (C:\...\node_modules\braces\index.js:82:17)
```

cc @naturalethic

**Comment by Conduitry** [comment]
I'm pretty sure this is caused by https://github.com/micromatch/micromatch#backslashes but I haven't tracked down how to resolve this.

**Comment by Conduitry** [comment]
I spent a while looking at this last night and I ended up in hell. I am in hell now.

**Comment by naturalethic** [comment]
Downgrading to chokidar@1.7.0 is a quick fix for this.

**Comment by naturalethic** [comment]
https://github.com/paulmillr/chokidar/issues/699

**Comment by naturalethic** [comment]
https://github.com/micromatch/braces/issues/16
