### ISSUE TITLE
Clashing routes should not cause the dev process to stop

### ISSUE THREAD

**Issue by neoel** [sveltejs/sapper#217]
Instead it should make a warning, and I'd say continue to use the old route untill it's deleted. 
Since in development flow it would be nice to not have to restart the server :).

```
/home/dexter/.nvm/versions/node/v8.10.0/lib/node_modules/sapper/dist/core.ts.js:204
        throw new Error("The " + a.file + " and " + b.file + " routes clash");
        ^

Error: The inventory/index.html and inventory.html routes clash
    at /home/dexter/.nvm/versions/node/v8.10.0/lib/node_modules/sapper/dist/core.ts.js:204:15
    at Array.sort (native)
    at Object.create_routes (/home/dexter/.nvm/versions/node/v8.10.0/lib/node_modules/sapper/dist/core.ts.js:172:10)
    at FSWatcher.<anonymous> (/home/dexter/.nvm/versions/node/v8.10.0/lib/node_modules/sapper/dist/dev.ts.js:164:51)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSWatcher.<anonymous> (/home/dexter/.nvm/versions/node/v8.10.0/lib/node_modules/sapper/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/home/dexter/.nvm/versions/node/v8.10.0/lib/node_modules/sapper/node_modules/chokidar/index.js:241:5)
    at FSWatcher.NodeFsHandler._handleFile (/home/dexter/.nvm/versions/node/v8.10.0/lib/node_modules/sapper/node_modules/chokidar/lib/nodefs-handler.js:276:10)
    at FSWatcher.<anonymous> (/home/dexter/.nvm/versions/node/v8.10.0/lib/node_modules/sapper/node_modules/chokidar/lib/nodefs-handler.js:474:21)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by arxpoetica** [comment]
I'm encountering this too...I admit my use case is weird, but I have index.html and index.pug files sitting right next to each other. In my Sapper update, things won't run any longer so I have to figure out what to do...

**Comment by Rich-Harris** [comment]
It looks like this behaves correctly now — the build recovers when changes are made. So I'll close this
