### ISSUE TITLE
Routes clash error in dev server when editing file from `sveltejs/sapper-template` degit app

### ISSUE THREAD

**Issue by btakita** [sveltejs/sapper#220]
Run:
```
degit sveltejs/sapper-template my-app
cd my-app
ncu -au
yarn
npm run dev
```
Then edit `routes/index.html`

```
Error: The index.html and index.html___jb_tmp___ routes clash
    at /home/user/my-app/node_modules/sapper/dist/core.ts.js:204:15
    at Array.sort (native)
    at Object.create_routes (/home/user/my-app/node_modules/sapper/dist/core.ts.js:172:10)
    at FSWatcher.<anonymous> (/home/user/my-app/node_modules/sapper/dist/dev.ts.js:164:51)
    at FSWatcher.emit (events.js:180:13)
    at FSWatcher.<anonymous> (/home/user/my-app/node_modules/chokidar/index.js:199:15)
    at FSWatcher._emit (/home/user/my-app/node_modules/chokidar/index.js:241:5)
    at FSWatcher.NodeFsHandler._handleFile (/home/user/my-app/node_modules/chokidar/lib/nodefs-handler.js:276:10)
    at FSWatcher.<anonymous> (/home/user/my-app/node_modules/chokidar/lib/nodefs-handler.js:474:21)
    at FSReqWrap.oncomplete (fs.js:171:5)
```

As you can see above, I ran `npm-check-updates`.
Here is my `package.json`:

```json
{
  "name": "TODO",
  "description": "TODO",
  "version": "0.0.1",
  "scripts": {
    "dev": "sapper dev",
    "build": "sapper build",
    "export": "sapper export",
    "start": "sapper start",
    "cy:run": "cypress run",
    "cy:open": "cypress open",
    "test": "run-p --race dev cy:run"
  },
  "dependencies": {
    "compression": "^1.7.2",
    "npm-run-all": "^4.1.2",
    "polka": "^0.3.4",
    "sapper": "^0.10.2",
    "serve-static": "^1.13.2",
    "svelte": "^1.58.5",
    "svelte-loader": "^2.5.1",
    "webpack": "^4.4.1"
  }
}
```

**Comment by btakita** [comment]
https://github.com/sveltejs/sapper/issues/217

**Comment by btakita** [comment]
I'm using Webstorm, & it looks like Jetbrains IDE's create a temporary file:

`index.html___jb_tmp___` when the file updates

**Comment by Rich-Harris** [comment]
Thanks — in 0.19.2, files with extensions that aren't just `[a-z]+` are ignored, preventing these kinds of clashes
