### ISSUE TITLE
Internal Server Error for Production Build

### ISSUE THREAD

**Issue by Snugug** [sveltejs/sapper#225]
I've got a Sapper-based app that works fine in development mode, no errors, and builds fine for production. When I go to run it using `npm start` (`sapper start`) and I go to a page, I get the following error:

```
Error: TypeError: Assignment to constant variable.
    at At (analytics/build/server.js:1:42244)
    at st (analytics/build/server.js:1:42310)
    at handle_route (analytics/node_modules/sapper/dist/src/middleware.ts:326:6)
    at find_route (analytics/node_modules/sapper/dist/src/middleware.ts:378:62)
    at go (analytics/node_modules/sapper/dist/src/middleware.ts:395:5)
    at analytics/node_modules/sapper/dist/src/middleware.ts:397:6
    at analytics/node_modules/sapper/dist/src/middleware.ts:131:4
    at go (analytics/node_modules/sapper/dist/src/middleware.ts:395:5)
    at analytics/node_modules/sapper/dist/src/middleware.ts:397:6
    at analytics/node_modules/sapper/dist/src/middleware.ts:131:4
```

This appears to be a Sapper issue as the error appears to trace back to Sapper middleware. Resolved Sapper version from `package-lock.json`

```
"sapper": {
      "version": "0.10.2",
      "resolved": "https://registry.npmjs.org/sapper/-/sapper-0.10.2.tgz",
      "integrity": "sha512-bvf/BySTenIzf7GElKN/qjSqwND9THZKOTCVwUc9ULtJZuEvhuFOYvcYJ78aaEI0ZcgVjRgpH5tMUBqZ2r1Nvg==",
      "requires": {
        "cheerio": "1.0.0-rc.2",
        "chokidar": "2.0.3",
        "clorox": "1.0.3",
        "cookie": "0.3.1",
        "devalue": "1.0.3",
        "glob": "7.1.2",
        "html-minifier": "3.5.12",
        "mkdirp": "0.5.1",
        "node-fetch": "2.1.2",
        "port-authority": "1.0.3",
        "pretty-bytes": "4.0.2",
        "pretty-ms": "3.1.0",
        "require-relative": "0.8.7",
        "rimraf": "2.6.2",
        "sade": "1.4.0",
        "sander": "0.6.0",
        "source-map-support": "0.5.4",
        "tslib": "1.9.0",
        "url-parse": "1.2.0",
        "webpack-format-messages": "1.0.2"
      }
    },
```

**Comment by silentworks** [comment]
Have you tried the latest version? also what version of Node are you using?

**Comment by Rich-Harris** [comment]
Closing as there isn't anything we can do with this information
