### ISSUE TITLE
timeout during export on Windows 10 CMD & WSL

### ISSUE THREAD

**Issue by bryanwood** [sveltejs/sapper#244]
I'm getting a timeout error when running `export`, ~~but it only occurs when my laptops running on batteries (which is causing lower performance/slower builds).~~ ~~From the output I'm guessing it might be related to hitting some 5s timeout somewhere when webpack takes more than 5s to run?~~ I've had a run of `export` fail even when it was built in under 5s but anecdotally it always times out when performance is lower and infrequently when performance is higher.

This is running on Windows 10 CMD and WSL with new `npm install`'s when switching.

After looking for possible causes I found this:

https://github.com/Rich-Harris/port-authority/blob/a1e50d86232fa1236f127603c63360656355d9a7/src/wait.ts#L33

Code from link copied to below: 
```ts
function get_connection(port: number, cb: () => void) {
	let timeout: NodeJS.Timer;

	const socket = net.connect(port, 'localhost', () => {
		cb();
		socket.destroy();
		clearTimeout(timeout);
	});

	socket.on('error', () => {
		setTimeout(() => {
			get_connection(port, cb);
		}, 10);
	});

	timeout = setTimeout(() => {
		socket.destroy();
	}, 1000);
}
```

Changing that timeout for `socket.destory()` to 3000ms seems to make the issue go away in all cases.

Seems like maybe it takes >1s to acquire a socket on a slow enough machine? I'm not really sure.

Output when on battery:
WSL
```
Hash: 1415a618f62af901f2b5
Version: webpack 4.6.0
Time: 619ms
Built at: 2018-04-22 18:44:11
            Asset      Size  Chunks             Chunk Names
service-worker.js  3.42 KiB       0  [emitted]  service-worker
Entrypoint service-worker = service-worker.js
[0] ./app/service-worker.js + 1 modules 5.03 KiB {0} [built]
    | ./app/service-worker.js 2.3 KiB [built]
    | ./app/manifest/service-worker.js 2.73 KiB [built]

> Built in 8.7s. Crawling site...
Error: timed out waiting for connection
    at Timeout._onTimeout (/mnt/c/Users/bryan/Documents/GitHub/tale/node_modules/port-authority/dist/port-authority.cjs.js:109:20)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

and

CMD
```
Hash: 3c48360fd1660a6d4867
Version: webpack 4.6.0
Time: 699ms
Built at: 2018-04-22 18:50:36
            Asset      Size  Chunks             Chunk Names
service-worker.js  3.42 KiB       0  [emitted]  service-worker
Entrypoint service-worker = service-worker.js
[0] ./app/service-worker.js + 1 modules 5.03 KiB {0} [built]
    | ./app/service-worker.js 2.3 KiB [built]
    | ./app/manifest/service-worker.js 2.73 KiB [built]

> Built in 5.5s. Crawling site...
Error: timed out waiting for connection
    at Timeout._onTimeout (C:\Users\bryan\Documents\GitHub\tale\node_modules\port-authority\dist\port-authority.cjs.js:109:20)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

Output when plugged in:

WSL
```
Hash: f712bc3872cf420ec70f
Version: webpack 4.6.0
Time: 429ms
Built at: 2018-04-22 18:45:21
            Asset      Size  Chunks             Chunk Names
service-worker.js  3.42 KiB       0  [emitted]  service-worker
Entrypoint service-worker = service-worker.js
[0] ./app/service-worker.js + 1 modules 5.03 KiB {0} [built]
    | ./app/service-worker.js 2.3 KiB [built]
    | ./app/manifest/service-worker.js 2.73 KiB [built]

> Built in 4.9s. Crawling site...
index.html (5.93 kB)
services/index.html (8.07 kB)
> Received 404 response when fetching /services/screenwriting
> Received 404 response when fetching /services/art-and-design
projects/index.html (7.28 kB)
projects/australi/index.html (17.8 kB)
projects/wme/index.html (5.04 kB)
projects/sky-train/index.html (5.04 kB)
projects/the-tale-inn/index.html (5.05 kB)
people/index.html (6.23 kB)
> Received 404 response when fetching /people/tim
> Received 404 response when fetching /people/tomas
> Received 404 response when fetching /people/pius

> Finished in 8.6s. Type npx serve export to run the app.
```

and

CMD
```
Hash: e03f1020a662691e89fe
Version: webpack 4.6.0
Time: 427ms
Built at: 2018-04-22 18:51:27
            Asset      Size  Chunks             Chunk Names
service-worker.js  3.42 KiB       0  [emitted]  service-worker
Entrypoint service-worker = service-worker.js
[0] ./app/service-worker.js + 1 modules 5.03 KiB {0} [built]
    | ./app/service-worker.js 2.3 KiB [built]
    | ./app/manifest/service-worker.js 2.73 KiB [built]

> Built in 3.9s. Crawling site...
index.html (5.93 kB)
services/index.html (8.07 kB)
> Received 404 response when fetching /services/screenwriting
> Received 404 response when fetching /services/art-and-design
projects/index.html (7.28 kB)
projects/australi/index.html (17.8 kB)
projects/wme/index.html (5.04 kB)
projects/sky-train/index.html (5.04 kB)
projects/the-tale-inn/index.html (5.05 kB)
people/index.html (6.23 kB)
> Received 404 response when fetching /people/tim
> Received 404 response when fetching /people/tomas
> Received 404 response when fetching /people/pius

> Finished in 5.5s. Type npx serve export to run the app.
```

package.json
```
{
  "name": "TODO",
  "description": "TODO",
  "version": "0.0.1",
  "scripts": {
    "dev": "sapper dev",
    "build": "sapper build",
    "export": "sapper export",
    "start": "sapper start",
    "cy:run": "cypress run",
    "cy:open": "cypress open",
    "test": "run-p --race dev cy:run"
  },
  "dependencies": {
    "compression": "^1.7.1",
    "cross-env": "^5.1.3",
    "eases-jsnext": "^1.0.10",
    "node-fetch": "^4.1.2",
    "npm-run-all": "^4.1.2",
    "polka": "^0.3.4",
    "sapper": "^0.10.6",
    "serve-static": "^1.13.1",
    "svelte": "^2.1.0",
    "svelte-extras": "^2.0.2",
    "svelte-loader": "^2.8.1",
    "webpack": "^4.6.0"
  }
}
```

CMD - failed when plugged in.
```
Hash: 2dac3b5ffb306843724d
Version: webpack 4.6.0
Time: 485ms
Built at: 2018-04-22 19:12:39
            Asset      Size  Chunks             Chunk Names
service-worker.js  3.42 KiB       0  [emitted]  service-worker
Entrypoint service-worker = service-worker.js
[0] ./app/service-worker.js + 1 modules 5.03 KiB {0} [built]
    | ./app/service-worker.js 2.3 KiB [built]
    | ./app/manifest/service-worker.js 2.73 KiB [built]

> Built in 4.3s. Crawling site...
Error: timed out waiting for connection
    at Timeout._onTimeout (C:\Users\bryan\Documents\GitHub\tale\node_modules\port-authority\dist\port-authority.cjs.js:109:20)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by bryanwood** [comment]
Digging into this here: https://github.com/bryanwood/port-authority/tree/wait-under-cpu-load

**Comment by Conduitry** [comment]
Yeah I've experienced this on Windows as well, but I never dug into it too hard because I realized that the server was actually started and seemed to work. The error just seemed to be that the part checking to see whether the server had started wasn't working correctly or didn't wait for long enough or something.

**Comment by Rich-Harris** [comment]
Released a new version of port-authority (thanks for the PR), so *maybe* this is fixed now? 🤞

**Comment by Rich-Harris** [comment]
I'm going to close this, optimistically
