### ISSUE TITLE
Import error for store.js with rollup

### ISSUE THREAD

**Issue by nlsw** [sveltejs/sapper#387]
There seems to be an error with importing the svelte store while using rollup:

```
/node_modules/svelte/store.js:1
(function (exports, require, module, __filename, __dirname) { import {
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/.sapper/dev/server.js:8136:19)
```

This is the most relevant part of my package.json:
```
{
  "dependencies": {
    "polka": "^0.4.0",
    "sapper": "^0.18.3",
    "sirv": "^0.2.0",
    "svelte-extras": "^2.0.2"
  },
  "devDependencies": {
    "chokidar": "^2.0.4",
    "rollup": "^0.65.0",
    "rollup-plugin-commonjs": "^9.1.6",
    "rollup-plugin-loadz0r": "^0.4.0",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-replace": "^2.0.0",
    "rollup-plugin-svelte": "^4.2.1",
    "rollup-plugin-terser": "^1.0.1",
    "svelte": "^2.13.2"
  }
}
```

I'm not sure if svelte-extras should be in dep's or in devDep's, but in both cases the error remains.

**Comment by Rich-Harris** [comment]
I'm 99% sure this indicates that `svelte/store.js` isn't being included in the server bundle. What does your server config look like?

**Comment by nlsw** [comment]
Do you mean the `app/server.js` file? That's the same as it was in the webpack version. It's quite a complicated one with different levels of authorization and authorization, but in essence:

```
import polka from 'polka';
import sapper from 'sapper';
import { manifest } from './manifest/server.js';
[...]
const { Store } = require('svelte/store.js');

polka().use(
	[...]
	sapper({
		manifest,
		store: req => {
			[...]
	       		return new Store({
       				user: {local, ip, ...req.session.user},
       			});
        	},
	}),
)
.listen(process.env.PORT)
.catch(err => console.log('error', err))
```

The `rollup/server.config.js` file is a copy from the sapper-template-rollup repo.

**Comment by Rich-Harris** [comment]
Change this line:

```diff
-const { Store } = require('svelte/store.js');
+import { Store } from 'svelte/store.js';
```

**Comment by nlsw** [comment]
Great! It's working now. I've noticed that you've referenced this in the pull request. Sorry, I should have noticed that before. Thanks for your great work!
