### ISSUE TITLE
Install instructions from guide no longer work

### ISSUE THREAD

**Issue by antony** [sveltejs/sapper#398]
When I follow the basic instructions from the guide:

* npx degit sveltejs/sapper-template my-app
* cd my-app
* npm install
* npm run dev

I am met with the following error:

```bash
$ npm run dev

> TODO@0.0.1 dev /home/ant/Projects/my-app> sapper dev

(node:31451) UnhandledPromiseRejectionWarning: Error: Cannot find module 'sapper/config/webpack.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/ant/Projects/my-app/webpack/client.config.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
(node:31451) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31451) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Rich-Harris** [comment]
Whoops! Try now — should be fixed (sapper-template had a dependency on an out-of-date Sapper version)

**Comment by antony** [comment]
Thanks for the quick fix... but it results in an exciting new error:

```bash
ant@convey:~/Projects/my-app$ npm install
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/map-visit-cdaabc42/package.json'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/map-visit-cdaabc42/README.md'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/object-visit-a8ecc14d/package.json'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/define-properties-ff35dcfe/package.json'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/map-visit-cdaabc42/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/object-visit-a8ecc14d/README.md'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/define-properties-ff35dcfe/.editorconfig'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/map-visit-cdaabc42/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/object-visit-a8ecc14d/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/define-properties-ff35dcfe/.eslintrc'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/object-visit-a8ecc14d/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/define-properties-ff35dcfe/.jscs.json'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/define-properties-ff35dcfe/.travis.yml'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/define-properties-ff35dcfe/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/define-properties-ff35dcfe/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/uglify-es-8c438a51/tools/exit.js'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/define-properties-ff35dcfe/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/uglify-es-8c438a51/tools/exports.js'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/define-properties-ff35dcfe/README.md'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/uglify-es-8c438a51/tools/node.js'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/uglify-es-8c438a51/tools/props.html'
npm WARN tar ENOENT: no such file or directory, open '/home/ant/Projects/my-app/node_modules/.staging/pako-f852f1ca/dist/pako.min.js'
npm WARN TODO@0.0.1 No repository field.
npm WARN TODO@0.0.1 No license field.

npm ERR! path /home/ant/Projects/my-app/node_modules/.staging/svelte-412ae09f/node_modules/@babel/code-frame
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/ant/Projects/my-app/node_modules/.staging/svelte-412ae09f/node_modules/@babel/code-frame' -> '/home/ant/Projects/my-app/node_modules/.staging/@babel/code-frame-f91db956'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ant/.npm/_logs/2018-08-31T15_03_20_090Z-debug.log
```

**Comment by Rich-Harris** [comment]
huh... must be a bad lockfile. one sec...

**Comment by antony** [comment]
Deleted the lockfile but now I get:

```bash
ant@convey:~/Projects/my-app$ npm run dev

> TODO@0.0.1 dev /home/ant/Projects/my-app
> sapper dev

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'webpack-format-messages'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at new WebpackResult (/home/ant/Projects/my-app/node_modules/sapper/dist/core.js:635:31)
    at Watching.handler (/home/ant/Projects/my-app/node_modules/sapper/dist/core.js:831:30)
    at compiler.hooks.done.callAsync (/home/ant/Projects/my-app/node_modules/webpack/lib/Watching.js:100:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ant/Projects/my-app/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/ant/Projects/my-app/node_modules/tapable/lib/Hook.js:35:21)
    at Watching._done (/home/ant/Projects/my-app/node_modules/webpack/lib/Watching.js:99:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TODO@0.0.1 dev: `sapper dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TODO@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ant/.npm/_logs/2018-08-31T15_26_07_684Z-debug.log
```

**Comment by antony** [comment]
Installing the missing webpack-format-messages module seems to fix it :)

**Comment by Rich-Harris** [comment]
yeah, that was moved to dev dependencies recently but wasn't getting bundled because it used a `require` instead of an `import`... fixed in Sapper 0.18.6

**Comment by Rich-Harris** [comment]
updated sapper-template — should all be fixed now 🤞

**Comment by antony** [comment]
Works a treat!

**Comment by Rich-Harris** [comment]
fantastic! thanks for flagging it up 🍻

**Comment by son-nguyen-301** [comment]
I still got this issue on Sep 02 2020

**Comment by son-nguyen-301** [comment]
> I still got this issue on Sep 02 2020

Fixed. Clone the repo again and it worked. Don't know exacly why I did not work for the first repo :|
