### ISSUE TITLE
Importing External Components

### ISSUE THREAD

**Issue by evanleck** [sveltejs/sapper#637]
I see that [rollup-plugin-svelte allows exporting multiple components](https://github.com/rollup/rollup-plugin-svelte/issues/39) via `pkg.svelte` but I get an error on the server every time I try to import them. I'm using the rollup-v3 version of the Sapper template.

My component library's `package.json` has `"svelte": "src/index.js"` and my `index.js` is just exporting a bunch of Svelte components:

```js
import Button from './Button.svelte'
import Card from './Card.svelte'
import Form from './Form.svelte'
import Input from './Input.svelte'
import ListGroup from './ListGroup.svelte'
import ListItem from './ListItem.svelte'
import NavigationItem from './NavigationItem.svelte'
import Notification from './Notification.svelte'
import PageHeader from './PageHeader.svelte'
import Time from './Time.svelte'
import TitleBar from './TitleBar.svelte'

export {
  Button,
  Card,
  Form,
  Input,
  ListGroup,
  ListItem,
  Notification,
  NavigationItem,
  PageHeader,
  Time,
  TitleBar
}
```

The client boots fine, but the server crashes:

```
(function (exports, require, module, __filename, __dirname) { import Button from './Button.svelte'
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
> Server crashed
```

It looks to me like an ESM vs. CommonJS issue, but I'm not 100% sure. Any help would be appreciated, thanks!

**Comment by evanleck** [comment]
It looks like moving the dependency to `devDependencies` [as mentioned here](https://github.com/sveltejs/sapper-template#using-external-components-with-webpack) did the trick. I've run into another issue, but I don't think it's related.
