### ISSUE TITLE
Override route regexp in .svelte file

### ISSUE THREAD

**Issue by IlyaSemenov** [sveltejs/sapper#706]
Currently, per <https://sapper.svelte.dev/docs#Regexes_in_routes>, it's not possible to use complex regular expressions in routes:

> For example, src/routes/items/[id([0-9]+)].svelte would only match numeric IDs — /items/123 would match, but /items/xyz would not.
> Because of technical limitations, the following characters cannot be used: /, \, ?, :, ( and ).

However, I *do* need to use `/` and `\` in the regexp.

I need to have the following routes:

`.*/` -> category page (e.g. `/foo/bar/baz/` - unlimited nesting)
`.*/[^/]+\.html` -> item page (e.g. `/foo/bar/baz/xyzzy.html`)

Can we allow to override the full route match string in the corresponding `.svelte` file? For instance, in my case I could have `[category].svelte`:

```html
<script context="module">
export default route = '.*/'
</script>
```

and `[item].svelte`:

```html
<script context="module">
export default route = '.*/[^/]+\\.html'
</script>
```

Or do you see a better approach?

**Comment by mrkishi** [comment]
I think allowing custom param matching would be a nice feature, but for what you need, specifically, we have rest routes. I believe your exact structure could be specified like this:

```
- /routes/[...categories]/[item].html.svelte
- /routes/[...categories].svelte (or routes/[...categories]/index.svelte)
```

It seems we haven't documented this yet!

**Comment by IlyaSemenov** [comment]
Thank you for the advice. This workaround will work for now, although ultimately arbitrary regexp would be better.

However, **your example doesn't work fully!**

* `/routes/[...categories]/[item].html.svelte` - this one works
* neither `/routes/[...categories].svelte` or `/routes/[...categories]/index.svelte` work:

```
❯ yarn dev
yarn run v1.16.0
warning package.json: No license field
$ sapper dev
✗ client
src/routes/[...categories]/index.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: TypeError: TypeError: Cannot read property 'toUpperCase' of undefined
✗ server
src/routes/[...categories]/index.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: TypeError: TypeError: Cannot read property 'toUpperCase' of undefined
✔ service worker (168ms)
webpack:///./src/routes/%5B...categories%5D/index.svelte?:1
throw new Error("Module build failed (from ./node_modules/svelte-loader/index.js):\nError: TypeError: TypeError: Cannot read property 'toUpperCase' of undefined\n    at preprocess.then.catch.err (/Users/semenov/tmp/my-app/node_modules/svelte-loader/index.js:180:12)");
^

Error: Module build failed (from ./node_modules/svelte-loader/index.js):
Error: TypeError: TypeError: Cannot read property 'toUpperCase' of undefined
    at preprocess.then.catch.err (/Users/semenov/tmp/my-app/node_modules/svelte-loader/index.js:180:12)
    at eval (webpack:///./src/routes/%5B...categories%5D/index.svelte?:1:7)
    at Object../src/routes/[...categories]/index.svelte (/Users/semenov/tmp/my-app/__sapper__/dev/server/server.js:193:1)
    at __webpack_require__ (/Users/semenov/tmp/my-app/__sapper__/dev/server/server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/internal/manifest-server.mjs?:12:89)
    at Module../src/node_modules/@sapper/internal/manifest-server.mjs (/Users/semenov/tmp/my-app/__sapper__/dev/server/server.js:158:1)
    at __webpack_require__ (/Users/semenov/tmp/my-app/__sapper__/dev/server/server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/server.mjs?:5:83)
    at Module../src/node_modules/@sapper/server.mjs (/Users/semenov/tmp/my-app/__sapper__/dev/server/server.js:182:1)
    at __webpack_require__ (/Users/semenov/tmp/my-app/__sapper__/dev/server/server.js:21:30)
    at eval (webpack:///./src/server.js?:8:72)
> Server crashed
```

Tested on a brand new install of `npx degit sveltejs/sapper-template#webpack my-app` with only one file added at `src/routes/[...categories]/index.svelte`:

```html
<h1>cat index</h1>
```

Should I rather open a new GitHub issue?
