### ISSUE TITLE
App.svelte calling setContext results in "Error: Function called outside component initialization" error

### ISSUE THREAD

**Issue by btakita** [sveltejs/sapper#769]
I'm not sure about the root cause, however the `setContext` generated inside of `App.svelte` is causing this issue.

Here's the stack trace:

```
Error: Function called outside component initialization
    at get_current_component (/home/brian/project/node_modules/svelte/internal/index.js:485:15)
    at Object.setContext (/home/brian/project/node_modules/svelte/internal/index.js:515:5)
    at /home/brian/project/packages/_web/__sapper__/dev/server/chunk-2b2cb289.js:1117:9
    at $$render (/home/brian/project/packages/_web/__sapper__/dev/server/chunk-79666caf.js:74:22)
    at Object.render (/home/brian/project/packages/_web/__sapper__/dev/server/chunk-79666caf.js:82:26)
    at handle_page (/home/brian/project/packages/_web/__sapper__/dev/server/server.js:9877:46)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by Conduitry** [comment]
Do you have a repro  for this?

**Comment by btakita** [comment]
I don't have a repro, but somehow both `svelte/store/index.mjs` & `svelte/store/index.js` were imported.
