### ISSUE TITLE
Stack traces could be better in general

### ISSUE THREAD

**Issue by arggh** [sveltejs/sapper#899]
**Is your feature request related to a problem? Please describe.**
Would be nice to have better stack traces and error messages.

One of my components was using `document` outside of `onmount`.

This is was not as helpful, as it could have been:
```
ReferenceError: document is not defined
    at create_ssr_component (/Users/arggh/app/__sapper__/dev/server/server.js:4733:11)
    at Object.$$render (/Users/arggh/app/__sapper__/dev/server/server.js:265:22)
    at create_ssr_component (/Users/arggh/app/__sapper__/dev/server/server.js:4772:59)
    at Object.$$render (/Users/arggh/app/__sapper__/dev/server/server.js:265:22)
    at create_ssr_component (/Users/arggh/app/__sapper__/dev/server/server.js:4958:41)
    at $$render (/Users/arggh/app/__sapper__/dev/server/server.js:265:22)
    at Object.render (/Users/arggh/app/__sapper__/dev/server/server.js:273:26)
    at handle_page (/Users/arggh/app/__sapper__/dev/server/server.js:7336:36)
    at <anonymous>
```

**Describe the solution you'd like**
I'd like to know where things are not working without combing through 50k lines of `server.js`, maybe even accompanied by a helpful message describing why it's not working and what should be done.

**How important is this feature to you?**
It's not a show stopper, but it sure does make Sapper feel unfinished and takes a toll on developer experience and productivity.

**Comment by benmccann** [comment]
There's a PR for this: https://github.com/sveltejs/sapper/pull/773
